const librarylist = [
  { id: "acf", href: "/detail/base/acf.html", texttag: "acf" },
  { id: "acf2AR", href: "/detail/base/acf2AR.html", texttag: "acf2AR" },
  { id: "add.scope", href: "/detail/base/addscope.html", texttag: "add.scope" },
  { id: "add1", href: "/detail/base/add1.html", texttag: "add1" },
  {
    id: "addmargins",
    href: "/detail/base/addmargins.html",
    texttag: "addmargins",
  },
  {
    id: "aggregate",
    href: "/detail/base/aggregate.html",
    texttag: "aggregate",
  },
  {
    id: "aggregate.data.frame",
    href: "/detail/base/aggregatedata.frame.html",
    texttag: "aggregate.data.frame",
  },
  {
    id: "aggregate.ts",
    href: "/detail/base/aggregatets.html",
    texttag: "aggregate.ts",
  },
  { id: "AIC", href: "/detail/base/AIC.html", texttag: "AIC" },
  { id: "alias", href: "/detail/base/alias.html", texttag: "alias" },
  { id: "anova", href: "/detail/base/anova.html", texttag: "anova" },
  {
    id: "ansari.test",
    href: "/detail/base/ansaritest.html",
    texttag: "ansari.test",
  },
  { id: "aov", href: "/detail/base/aov.html", texttag: "aov" },
  { id: "approx", href: "/detail/base/approx.html", texttag: "approx" },
  {
    id: "approxfun",
    href: "/detail/base/approxfun.html",
    texttag: "approxfun",
  },
  { id: "ar", href: "/detail/base/ar.html", texttag: "ar" },
  { id: "ar.burg", href: "/detail/base/arburg.html", texttag: "ar.burg" },
  { id: "ar.mle", href: "/detail/base/armle.html", texttag: "ar.mle" },
  { id: "ar.ols", href: "/detail/base/arols.html", texttag: "ar.ols" },
  { id: "ar.yw", href: "/detail/base/aryw.html", texttag: "ar.yw" },
  { id: "arima", href: "/detail/base/arima.html", texttag: "arima" },
  { id: "arima.sim", href: "/detail/base/arimasim.html", texttag: "arima.sim" },
  { id: "arima0", href: "/detail/base/arima0.html", texttag: "arima0" },
  {
    id: "arima0.diag",
    href: "/detail/base/arima0diag.html",
    texttag: "arima0.diag",
  },
  { id: "ARMAacf", href: "/detail/base/ARMAacf.html", texttag: "ARMAacf" },
  { id: "ARMAtoMA", href: "/detail/base/ARMAtoMA.html", texttag: "ARMAtoMA" },
  {
    id: "as.dendrogram",
    href: "/detail/base/asdendrogram.html",
    texttag: "as.dendrogram",
  },
  { id: "as.dist", href: "/detail/base/asdist.html", texttag: "as.dist" },
  {
    id: "as.formula",
    href: "/detail/base/asformula.html",
    texttag: "as.formula",
  },
  { id: "as.hclust", href: "/detail/base/ashclust.html", texttag: "as.hclust" },
  {
    id: "as.stepfun",
    href: "/detail/base/asstepfun.html",
    texttag: "as.stepfun",
  },
  { id: "as.ts", href: "/detail/base/asts.html", texttag: "as.ts" },
  {
    id: "asOneSidedFormula",
    href: "/detail/base/asOneSidedFormula.html",
    texttag: "asOneSidedFormula",
  },
  { id: "ave", href: "/detail/base/ave.html", texttag: "ave" },
  {
    id: "bandwidth.kernel",
    href: "/detail/base/bandwidthkernel.html",
    texttag: "bandwidth.kernel",
  },
  {
    id: "bartlett.test",
    href: "/detail/base/bartletttest.html",
    texttag: "bartlett.test",
  },
  { id: "BIC", href: "/detail/base/BIC.html", texttag: "BIC" },
  {
    id: "binom.test",
    href: "/detail/base/binomtest.html",
    texttag: "binom.test",
  },
  { id: "binomial", href: "/detail/base/binomial.html", texttag: "binomial" },
  { id: "biplot", href: "/detail/base/biplot.html", texttag: "biplot" },
  { id: "Box.test", href: "/detail/base/Boxtest.html", texttag: "Box.test" },
  { id: "bw.bcv", href: "/detail/base/bwbcv.html", texttag: "bw.bcv" },
  { id: "bw.nrd", href: "/detail/base/bwnrd.html", texttag: "bw.nrd" },
  { id: "bw.nrd0", href: "/detail/base/bwnrd0.html", texttag: "bw.nrd0" },
  { id: "bw.SJ", href: "/detail/base/bwSJ.html", texttag: "bw.SJ" },
  { id: "bw.ucv", href: "/detail/base/bwucv.html", texttag: "bw.ucv" },
  { id: "C", href: "/detail/base/C.html", texttag: "C" },
  { id: "cancor", href: "/detail/base/cancor.html", texttag: "cancor" },
  {
    id: "case.names",
    href: "/detail/base/casenames.html",
    texttag: "case.names",
  },
  { id: "ccf", href: "/detail/base/ccf.html", texttag: "ccf" },
  {
    id: "chisq.test",
    href: "/detail/base/chisqtest.html",
    texttag: "chisq.test",
  },
  { id: "cmdscale", href: "/detail/base/cmdscale.html", texttag: "cmdscale" },
  { id: "coef", href: "/detail/base/coef.html", texttag: "coef" },
  {
    id: "coefficients",
    href: "/detail/base/coefficients.html",
    texttag: "coefficients",
  },
  {
    id: "complete.cases",
    href: "/detail/base/completecases.html",
    texttag: "complete.cases",
  },
  { id: "confint", href: "/detail/base/confint.html", texttag: "confint" },
  {
    id: "confint.default",
    href: "/detail/base/confintdefault.html",
    texttag: "confint.default",
  },
  {
    id: "confint.lm",
    href: "/detail/base/confintlm.html",
    texttag: "confint.lm",
  },
  {
    id: "constrOptim",
    href: "/detail/base/constrOptim.html",
    texttag: "constrOptim",
  },
  {
    id: "contr.helmert",
    href: "/detail/base/contrhelmert.html",
    texttag: "contr.helmert",
  },
  {
    id: "contr.poly",
    href: "/detail/base/contrpoly.html",
    texttag: "contr.poly",
  },
  { id: "contr.SAS", href: "/detail/base/contrSAS.html", texttag: "contr.SAS" },
  { id: "contr.sum", href: "/detail/base/contrsum.html", texttag: "contr.sum" },
  {
    id: "contr.treatment",
    href: "/detail/base/contrtreatment.html",
    texttag: "contr.treatment",
  },
  {
    id: "contrasts",
    href: "/detail/base/contrasts.html",
    texttag: "contrasts",
  },
  {
    id: "contrasts<-",
    href: "/detail/base/contrasts<-.html",
    texttag: "contrasts<-",
  },
  { id: "convolve", href: "/detail/base/convolve.html", texttag: "convolve" },
  {
    id: "cooks.distance",
    href: "/detail/base/cooksdistance.html",
    texttag: "cooks.distance",
  },
  {
    id: "cophenetic",
    href: "/detail/base/cophenetic.html",
    texttag: "cophenetic",
  },
  { id: "cor", href: "/detail/base/cor.html", texttag: "cor" },
  { id: "cor.test", href: "/detail/base/cortest.html", texttag: "cor.test" },
  { id: "cov", href: "/detail/base/cov.html", texttag: "cov" },
  { id: "cov.wt", href: "/detail/base/covwt.html", texttag: "cov.wt" },
  { id: "cov2cor", href: "/detail/base/cov2cor.html", texttag: "cov2cor" },
  { id: "covratio", href: "/detail/base/covratio.html", texttag: "covratio" },
  { id: "cpgram", href: "/detail/base/cpgram.html", texttag: "cpgram" },
  { id: "cutree", href: "/detail/base/cutree.html", texttag: "cutree" },
  { id: "cycle", href: "/detail/base/cycle.html", texttag: "cycle" },
  { id: "D", href: "/detail/base/D.html", texttag: "D" },
  { id: "dbeta", href: "/detail/base/dbeta.html", texttag: "dbeta" },
  { id: "dbinom", href: "/detail/base/dbinom.html", texttag: "dbinom" },
  { id: "dcauchy", href: "/detail/base/dcauchy.html", texttag: "dcauchy" },
  { id: "dchisq", href: "/detail/base/dchisq.html", texttag: "dchisq" },
  {
    id: "decompose",
    href: "/detail/base/decompose.html",
    texttag: "decompose",
  },
  {
    id: "delete.response",
    href: "/detail/base/deleteresponse.html",
    texttag: "delete.response",
  },
  { id: "deltat", href: "/detail/base/deltat.html", texttag: "deltat" },
  {
    id: "dendrapply",
    href: "/detail/base/dendrapply.html",
    texttag: "dendrapply",
  },
  { id: "density", href: "/detail/base/density.html", texttag: "density" },
  {
    id: "density.default",
    href: "/detail/base/densitydefault.html",
    texttag: "density.default",
  },
  { id: "deriv", href: "/detail/base/deriv.html", texttag: "deriv" },
  { id: "deriv3", href: "/detail/base/deriv3.html", texttag: "deriv3" },
  { id: "deviance", href: "/detail/base/deviance.html", texttag: "deviance" },
  { id: "dexp", href: "/detail/base/dexp.html", texttag: "dexp" },
  { id: "df", href: "/detail/base/df.html", texttag: "df" },
  { id: "df.kernel", href: "/detail/base/dfkernel.html", texttag: "df.kernel" },
  {
    id: "df.residual",
    href: "/detail/base/dfresidual.html",
    texttag: "df.residual",
  },
  {
    id: "DF2formula",
    href: "/detail/base/DF2formula.html",
    texttag: "DF2formula",
  },
  { id: "dfbeta", href: "/detail/base/dfbeta.html", texttag: "dfbeta" },
  { id: "dfbetas", href: "/detail/base/dfbetas.html", texttag: "dfbetas" },
  { id: "dffits", href: "/detail/base/dffits.html", texttag: "dffits" },
  { id: "dgamma", href: "/detail/base/dgamma.html", texttag: "dgamma" },
  { id: "dgeom", href: "/detail/base/dgeom.html", texttag: "dgeom" },
  { id: "dhyper", href: "/detail/base/dhyper.html", texttag: "dhyper" },
  { id: "diffinv", href: "/detail/base/diffinv.html", texttag: "diffinv" },
  { id: "dist", href: "/detail/base/dist.html", texttag: "dist" },
  { id: "dlnorm", href: "/detail/base/dlnorm.html", texttag: "dlnorm" },
  { id: "dlogis", href: "/detail/base/dlogis.html", texttag: "dlogis" },
  {
    id: "dmultinom",
    href: "/detail/base/dmultinom.html",
    texttag: "dmultinom",
  },
  { id: "dnbinom", href: "/detail/base/dnbinom.html", texttag: "dnbinom" },
  { id: "dnorm", href: "/detail/base/dnorm.html", texttag: "dnorm" },
  { id: "dpois", href: "/detail/base/dpois.html", texttag: "dpois" },
  {
    id: "drop.scope",
    href: "/detail/base/dropscope.html",
    texttag: "drop.scope",
  },
  {
    id: "drop.terms",
    href: "/detail/base/dropterms.html",
    texttag: "drop.terms",
  },
  { id: "drop1", href: "/detail/base/drop1.html", texttag: "drop1" },
  {
    id: "dsignrank",
    href: "/detail/base/dsignrank.html",
    texttag: "dsignrank",
  },
  { id: "dt", href: "/detail/base/dt.html", texttag: "dt" },
  {
    id: "dummy.coef",
    href: "/detail/base/dummycoef.html",
    texttag: "dummy.coef",
  },
  {
    id: "dummy.coef.lm",
    href: "/detail/base/dummycoef.lm.html",
    texttag: "dummy.coef.lm",
  },
  { id: "dunif", href: "/detail/base/dunif.html", texttag: "dunif" },
  { id: "dweibull", href: "/detail/base/dweibull.html", texttag: "dweibull" },
  { id: "dwilcox", href: "/detail/base/dwilcox.html", texttag: "dwilcox" },
  { id: "ecdf", href: "/detail/base/ecdf.html", texttag: "ecdf" },
  {
    id: "eff.aovlist",
    href: "/detail/base/effaovlist.html",
    texttag: "eff.aovlist",
  },
  { id: "effects", href: "/detail/base/effects.html", texttag: "effects" },
  { id: "embed", href: "/detail/base/embed.html", texttag: "embed" },
  { id: "end", href: "/detail/base/end.html", texttag: "end" },
  { id: "estVar", href: "/detail/base/estVar.html", texttag: "estVar" },
  {
    id: "expand.model.frame",
    href: "/detail/base/expandmodel.frame.html",
    texttag: "expand.model.frame",
  },
  {
    id: "extractAIC",
    href: "/detail/base/extractAIC.html",
    texttag: "extractAIC",
  },
  { id: "factanal", href: "/detail/base/factanal.html", texttag: "factanal" },
  {
    id: "factor.scope",
    href: "/detail/base/factorscope.html",
    texttag: "factor.scope",
  },
  { id: "family", href: "/detail/base/family.html", texttag: "family" },
  { id: "fft", href: "/detail/base/fft.html", texttag: "fft" },
  { id: "filter", href: "/detail/base/filter.html", texttag: "filter" },
  {
    id: "fisher.test",
    href: "/detail/base/fishertest.html",
    texttag: "fisher.test",
  },
  { id: "fitted", href: "/detail/base/fitted.html", texttag: "fitted" },
  {
    id: "fitted.values",
    href: "/detail/base/fittedvalues.html",
    texttag: "fitted.values",
  },
  { id: "fivenum", href: "/detail/base/fivenum.html", texttag: "fivenum" },
  {
    id: "fligner.test",
    href: "/detail/base/flignertest.html",
    texttag: "fligner.test",
  },
  { id: "formula", href: "/detail/base/formula.html", texttag: "formula" },
  {
    id: "frequency",
    href: "/detail/base/frequency.html",
    texttag: "frequency",
  },
  {
    id: "friedman.test",
    href: "/detail/base/friedmantest.html",
    texttag: "friedman.test",
  },
  { id: "ftable", href: "/detail/base/ftable.html", texttag: "ftable" },
  { id: "Gamma", href: "/detail/base/Gamma.html", texttag: "Gamma" },
  { id: "gaussian", href: "/detail/base/gaussian.html", texttag: "gaussian" },
  {
    id: "get_all_vars",
    href: "/detail/base/get_all_vars.html",
    texttag: "get_all_vars",
  },
  { id: "getCall", href: "/detail/base/getCall.html", texttag: "getCall" },
  {
    id: "getInitial",
    href: "/detail/base/getInitial.html",
    texttag: "getInitial",
  },
  { id: "glm", href: "/detail/base/glm.html", texttag: "glm" },
  {
    id: "glm.control",
    href: "/detail/base/glmcontrol.html",
    texttag: "glm.control",
  },
  { id: "glm.fit", href: "/detail/base/glmfit.html", texttag: "glm.fit" },
  { id: "hasTsp", href: "/detail/base/hasTsp.html", texttag: "hasTsp" },
  { id: "hat", href: "/detail/base/hat.html", texttag: "hat" },
  {
    id: "hatvalues",
    href: "/detail/base/hatvalues.html",
    texttag: "hatvalues",
  },
  { id: "hclust", href: "/detail/base/hclust.html", texttag: "hclust" },
  { id: "heatmap", href: "/detail/base/heatmap.html", texttag: "heatmap" },
  {
    id: "HoltWinters",
    href: "/detail/base/HoltWinters.html",
    texttag: "HoltWinters",
  },
  {
    id: "influence",
    href: "/detail/base/influence.html",
    texttag: "influence",
  },
  {
    id: "influence.measures",
    href: "/detail/base/influencemeasures.html",
    texttag: "influence.measures",
  },
  {
    id: "integrate",
    href: "/detail/base/integrate.html",
    texttag: "integrate",
  },
  {
    id: "interaction.plot",
    href: "/detail/base/interactionplot.html",
    texttag: "interaction.plot",
  },
  {
    id: "inverse.gaussian",
    href: "/detail/base/inversegaussian.html",
    texttag: "inverse.gaussian",
  },
  { id: "IQR", href: "/detail/base/IQR.html", texttag: "IQR" },
  {
    id: "is.empty.model",
    href: "/detail/base/isempty.model.html",
    texttag: "is.empty.model",
  },
  { id: "is.leaf", href: "/detail/base/isleaf.html", texttag: "is.leaf" },
  { id: "is.mts", href: "/detail/base/ismts.html", texttag: "is.mts" },
  {
    id: "is.stepfun",
    href: "/detail/base/isstepfun.html",
    texttag: "is.stepfun",
  },
  { id: "is.ts", href: "/detail/base/ists.html", texttag: "is.ts" },
  {
    id: "is.tskernel",
    href: "/detail/base/istskernel.html",
    texttag: "is.tskernel",
  },
  { id: "isoreg", href: "/detail/base/isoreg.html", texttag: "isoreg" },
  {
    id: "KalmanForecast",
    href: "/detail/base/KalmanForecast.html",
    texttag: "KalmanForecast",
  },
  {
    id: "KalmanLike",
    href: "/detail/base/KalmanLike.html",
    texttag: "KalmanLike",
  },
  {
    id: "KalmanRun",
    href: "/detail/base/KalmanRun.html",
    texttag: "KalmanRun",
  },
  {
    id: "KalmanSmooth",
    href: "/detail/base/KalmanSmooth.html",
    texttag: "KalmanSmooth",
  },
  {
    id: "kernapply",
    href: "/detail/base/kernapply.html",
    texttag: "kernapply",
  },
  { id: "kernel", href: "/detail/base/kernel.html", texttag: "kernel" },
  { id: "kmeans", href: "/detail/base/kmeans.html", texttag: "kmeans" },
  { id: "knots", href: "/detail/base/knots.html", texttag: "knots" },
  {
    id: "kruskal.test",
    href: "/detail/base/kruskaltest.html",
    texttag: "kruskal.test",
  },
  { id: "ks.test", href: "/detail/base/kstest.html", texttag: "ks.test" },
  { id: "ksmooth", href: "/detail/base/ksmooth.html", texttag: "ksmooth" },
  { id: "lag", href: "/detail/base/lag.html", texttag: "lag" },
  { id: "lag.plot", href: "/detail/base/lagplot.html", texttag: "lag.plot" },
  { id: "line", href: "/detail/base/line.html", texttag: "line" },
  { id: "lm", href: "/detail/base/lm.html", texttag: "lm" },
  { id: "lm.fit", href: "/detail/base/lmfit.html", texttag: "lm.fit" },
  {
    id: "lm.influence",
    href: "/detail/base/lminfluence.html",
    texttag: "lm.influence",
  },
  { id: "lm.wfit", href: "/detail/base/lmwfit.html", texttag: "lm.wfit" },
  { id: "loadings", href: "/detail/base/loadings.html", texttag: "loadings" },
  { id: "loess", href: "/detail/base/loess.html", texttag: "loess" },
  {
    id: "loess.control",
    href: "/detail/base/loesscontrol.html",
    texttag: "loess.control",
  },
  {
    id: "loess.smooth",
    href: "/detail/base/loesssmooth.html",
    texttag: "loess.smooth",
  },
  { id: "logLik", href: "/detail/base/logLik.html", texttag: "logLik" },
  { id: "loglin", href: "/detail/base/loglin.html", texttag: "loglin" },
  { id: "lowess", href: "/detail/base/lowess.html", texttag: "lowess" },
  { id: "ls.diag", href: "/detail/base/lsdiag.html", texttag: "ls.diag" },
  { id: "ls.print", href: "/detail/base/lsprint.html", texttag: "ls.print" },
  { id: "lsfit", href: "/detail/base/lsfit.html", texttag: "lsfit" },
  { id: "mad", href: "/detail/base/mad.html", texttag: "mad" },
  {
    id: "mahalanobis",
    href: "/detail/base/mahalanobis.html",
    texttag: "mahalanobis",
  },
  { id: "make.link", href: "/detail/base/makelink.html", texttag: "make.link" },
  {
    id: "makeARIMA",
    href: "/detail/base/makeARIMA.html",
    texttag: "makeARIMA",
  },
  {
    id: "makepredictcall",
    href: "/detail/base/makepredictcall.html",
    texttag: "makepredictcall",
  },
  { id: "manova", href: "/detail/base/manova.html", texttag: "manova" },
  {
    id: "mantelhaen.test",
    href: "/detail/base/mantelhaentest.html",
    texttag: "mantelhaen.test",
  },
  {
    id: "mauchly.test",
    href: "/detail/base/mauchlytest.html",
    texttag: "mauchly.test",
  },
  {
    id: "mcnemar.test",
    href: "/detail/base/mcnemartest.html",
    texttag: "mcnemar.test",
  },
  { id: "median", href: "/detail/base/median.html", texttag: "median" },
  {
    id: "median.default",
    href: "/detail/base/mediandefault.html",
    texttag: "median.default",
  },
  {
    id: "medpolish",
    href: "/detail/base/medpolish.html",
    texttag: "medpolish",
  },
  {
    id: "model.extract",
    href: "/detail/base/modelextract.html",
    texttag: "model.extract",
  },
  {
    id: "model.frame",
    href: "/detail/base/modelframe.html",
    texttag: "model.frame",
  },
  {
    id: "model.frame.default",
    href: "/detail/base/modelframe.default.html",
    texttag: "model.frame.default",
  },
  {
    id: "model.matrix",
    href: "/detail/base/modelmatrix.html",
    texttag: "model.matrix",
  },
  {
    id: "model.matrix.default",
    href: "/detail/base/modelmatrix.default.html",
    texttag: "model.matrix.default",
  },
  {
    id: "model.matrix.lm",
    href: "/detail/base/modelmatrix.lm.html",
    texttag: "model.matrix.lm",
  },
  {
    id: "model.offset",
    href: "/detail/base/modeloffset.html",
    texttag: "model.offset",
  },
  {
    id: "model.response",
    href: "/detail/base/modelresponse.html",
    texttag: "model.response",
  },
  {
    id: "model.tables",
    href: "/detail/base/modeltables.html",
    texttag: "model.tables",
  },
  {
    id: "model.weights",
    href: "/detail/base/modelweights.html",
    texttag: "model.weights",
  },
  {
    id: "monthplot",
    href: "/detail/base/monthplot.html",
    texttag: "monthplot",
  },
  { id: "mood.test", href: "/detail/base/moodtest.html", texttag: "mood.test" },
  { id: "mvfft", href: "/detail/base/mvfft.html", texttag: "mvfft" },
  { id: "na.action", href: "/detail/base/naaction.html", texttag: "na.action" },
  {
    id: "na.contiguous",
    href: "/detail/base/nacontiguous.html",
    texttag: "na.contiguous",
  },
  {
    id: "na.exclude",
    href: "/detail/base/naexclude.html",
    texttag: "na.exclude",
  },
  { id: "na.fail", href: "/detail/base/nafail.html", texttag: "na.fail" },
  { id: "na.omit", href: "/detail/base/naomit.html", texttag: "na.omit" },
  { id: "na.pass", href: "/detail/base/napass.html", texttag: "na.pass" },
  {
    id: "napredict",
    href: "/detail/base/napredict.html",
    texttag: "napredict",
  },
  { id: "naprint", href: "/detail/base/naprint.html", texttag: "naprint" },
  { id: "naresid", href: "/detail/base/naresid.html", texttag: "naresid" },
  { id: "nextn", href: "/detail/base/nextn.html", texttag: "nextn" },
  { id: "nlm", href: "/detail/base/nlm.html", texttag: "nlm" },
  { id: "nlminb", href: "/detail/base/nlminb.html", texttag: "nlminb" },
  { id: "nls", href: "/detail/base/nls.html", texttag: "nls" },
  {
    id: "nls.control",
    href: "/detail/base/nlscontrol.html",
    texttag: "nls.control",
  },
  {
    id: "NLSstAsymptotic",
    href: "/detail/base/NLSstAsymptotic.html",
    texttag: "NLSstAsymptotic",
  },
  {
    id: "NLSstClosestX",
    href: "/detail/base/NLSstClosestX.html",
    texttag: "NLSstClosestX",
  },
  {
    id: "NLSstLfAsymptote",
    href: "/detail/base/NLSstLfAsymptote.html",
    texttag: "NLSstLfAsymptote",
  },
  {
    id: "NLSstRtAsymptote",
    href: "/detail/base/NLSstRtAsymptote.html",
    texttag: "NLSstRtAsymptote",
  },
  { id: "nobs", href: "/detail/base/nobs.html", texttag: "nobs" },
  {
    id: "numericDeriv",
    href: "/detail/base/numericDeriv.html",
    texttag: "numericDeriv",
  },
  { id: "offset", href: "/detail/base/offset.html", texttag: "offset" },
  {
    id: "oneway.test",
    href: "/detail/base/onewaytest.html",
    texttag: "oneway.test",
  },
  { id: "optim", href: "/detail/base/optim.html", texttag: "optim" },
  {
    id: "optimHess",
    href: "/detail/base/optimHess.html",
    texttag: "optimHess",
  },
  { id: "optimise", href: "/detail/base/optimise.html", texttag: "optimise" },
  { id: "optimize", href: "/detail/base/optimize.html", texttag: "optimize" },
  {
    id: "order.dendrogram",
    href: "/detail/base/orderdendrogram.html",
    texttag: "order.dendrogram",
  },
  { id: "p.adjust", href: "/detail/base/padjust.html", texttag: "p.adjust" },
  {
    id: "p.adjust.methods",
    href: "/detail/base/padjust.methods.html",
    texttag: "p.adjust.methods",
  },
  { id: "pacf", href: "/detail/base/pacf.html", texttag: "pacf" },
  { id: "Pair", href: "/detail/base/Pair.html", texttag: "Pair" },
  {
    id: "pairwise.prop.test",
    href: "/detail/base/pairwiseprop.test.html",
    texttag: "pairwise.prop.test",
  },
  {
    id: "pairwise.t.test",
    href: "/detail/base/pairwiset.test.html",
    texttag: "pairwise.t.test",
  },
  {
    id: "pairwise.table",
    href: "/detail/base/pairwisetable.html",
    texttag: "pairwise.table",
  },
  {
    id: "pairwise.wilcox.test",
    href: "/detail/base/pairwisewilcox.test.html",
    texttag: "pairwise.wilcox.test",
  },
  { id: "pbeta", href: "/detail/base/pbeta.html", texttag: "pbeta" },
  { id: "pbinom", href: "/detail/base/pbinom.html", texttag: "pbinom" },
  {
    id: "pbirthday",
    href: "/detail/base/pbirthday.html",
    texttag: "pbirthday",
  },
  { id: "pcauchy", href: "/detail/base/pcauchy.html", texttag: "pcauchy" },
  { id: "pchisq", href: "/detail/base/pchisq.html", texttag: "pchisq" },
  { id: "pexp", href: "/detail/base/pexp.html", texttag: "pexp" },
  { id: "pf", href: "/detail/base/pf.html", texttag: "pf" },
  { id: "pgamma", href: "/detail/base/pgamma.html", texttag: "pgamma" },
  { id: "pgeom", href: "/detail/base/pgeom.html", texttag: "pgeom" },
  { id: "phyper", href: "/detail/base/phyper.html", texttag: "phyper" },
  { id: "plclust", href: "/detail/base/plclust.html", texttag: "plclust" },
  { id: "plnorm", href: "/detail/base/plnorm.html", texttag: "plnorm" },
  { id: "plogis", href: "/detail/base/plogis.html", texttag: "plogis" },
  { id: "plot.ecdf", href: "/detail/base/plotecdf.html", texttag: "plot.ecdf" },
  {
    id: "plot.spec.coherency",
    href: "/detail/base/plotspec.coherency.html",
    texttag: "plot.spec.coherency",
  },
  {
    id: "plot.spec.phase",
    href: "/detail/base/plotspec.phase.html",
    texttag: "plot.spec.phase",
  },
  {
    id: "plot.stepfun",
    href: "/detail/base/plotstepfun.html",
    texttag: "plot.stepfun",
  },
  { id: "plot.ts", href: "/detail/base/plotts.html", texttag: "plot.ts" },
  { id: "pnbinom", href: "/detail/base/pnbinom.html", texttag: "pnbinom" },
  { id: "pnorm", href: "/detail/base/pnorm.html", texttag: "pnorm" },
  { id: "poisson", href: "/detail/base/poisson.html", texttag: "poisson" },
  {
    id: "poisson.test",
    href: "/detail/base/poissontest.html",
    texttag: "poisson.test",
  },
  { id: "poly", href: "/detail/base/poly.html", texttag: "poly" },
  { id: "polym", href: "/detail/base/polym.html", texttag: "polym" },
  { id: "power", href: "/detail/base/power.html", texttag: "power" },
  {
    id: "power.anova.test",
    href: "/detail/base/poweranova.test.html",
    texttag: "power.anova.test",
  },
  {
    id: "power.prop.test",
    href: "/detail/base/powerprop.test.html",
    texttag: "power.prop.test",
  },
  {
    id: "power.t.test",
    href: "/detail/base/powert.test.html",
    texttag: "power.t.test",
  },
  { id: "PP.test", href: "/detail/base/PPtest.html", texttag: "PP.test" },
  { id: "ppoints", href: "/detail/base/ppoints.html", texttag: "ppoints" },
  { id: "ppois", href: "/detail/base/ppois.html", texttag: "ppois" },
  { id: "ppr", href: "/detail/base/ppr.html", texttag: "ppr" },
  { id: "prcomp", href: "/detail/base/prcomp.html", texttag: "prcomp" },
  { id: "predict", href: "/detail/base/predict.html", texttag: "predict" },
  {
    id: "predict.glm",
    href: "/detail/base/predictglm.html",
    texttag: "predict.glm",
  },
  {
    id: "predict.lm",
    href: "/detail/base/predictlm.html",
    texttag: "predict.lm",
  },
  { id: "preplot", href: "/detail/base/preplot.html", texttag: "preplot" },
  { id: "princomp", href: "/detail/base/princomp.html", texttag: "princomp" },
  {
    id: "printCoefmat",
    href: "/detail/base/printCoefmat.html",
    texttag: "printCoefmat",
  },
  { id: "profile", href: "/detail/base/profile.html", texttag: "profile" },
  { id: "proj", href: "/detail/base/proj.html", texttag: "proj" },
  { id: "promax", href: "/detail/base/promax.html", texttag: "promax" },
  { id: "prop.test", href: "/detail/base/proptest.html", texttag: "prop.test" },
  {
    id: "prop.trend.test",
    href: "/detail/base/proptrend.test.html",
    texttag: "prop.trend.test",
  },
  {
    id: "psignrank",
    href: "/detail/base/psignrank.html",
    texttag: "psignrank",
  },
  { id: "pt", href: "/detail/base/pt.html", texttag: "pt" },
  { id: "ptukey", href: "/detail/base/ptukey.html", texttag: "ptukey" },
  { id: "punif", href: "/detail/base/punif.html", texttag: "punif" },
  { id: "pweibull", href: "/detail/base/pweibull.html", texttag: "pweibull" },
  { id: "pwilcox", href: "/detail/base/pwilcox.html", texttag: "pwilcox" },
  { id: "qbeta", href: "/detail/base/qbeta.html", texttag: "qbeta" },
  { id: "qbinom", href: "/detail/base/qbinom.html", texttag: "qbinom" },
  {
    id: "qbirthday",
    href: "/detail/base/qbirthday.html",
    texttag: "qbirthday",
  },
  { id: "qcauchy", href: "/detail/base/qcauchy.html", texttag: "qcauchy" },
  { id: "qchisq", href: "/detail/base/qchisq.html", texttag: "qchisq" },
  { id: "qexp", href: "/detail/base/qexp.html", texttag: "qexp" },
  { id: "qf", href: "/detail/base/qf.html", texttag: "qf" },
  { id: "qgamma", href: "/detail/base/qgamma.html", texttag: "qgamma" },
  { id: "qgeom", href: "/detail/base/qgeom.html", texttag: "qgeom" },
  { id: "qhyper", href: "/detail/base/qhyper.html", texttag: "qhyper" },
  { id: "qlnorm", href: "/detail/base/qlnorm.html", texttag: "qlnorm" },
  { id: "qlogis", href: "/detail/base/qlogis.html", texttag: "qlogis" },
  { id: "qnbinom", href: "/detail/base/qnbinom.html", texttag: "qnbinom" },
  { id: "qnorm", href: "/detail/base/qnorm.html", texttag: "qnorm" },
  { id: "qpois", href: "/detail/base/qpois.html", texttag: "qpois" },
  { id: "qqline", href: "/detail/base/qqline.html", texttag: "qqline" },
  { id: "qqnorm", href: "/detail/base/qqnorm.html", texttag: "qqnorm" },
  { id: "qqplot", href: "/detail/base/qqplot.html", texttag: "qqplot" },
  {
    id: "qsignrank",
    href: "/detail/base/qsignrank.html",
    texttag: "qsignrank",
  },
  { id: "qt", href: "/detail/base/qt.html", texttag: "qt" },
  { id: "qtukey", href: "/detail/base/qtukey.html", texttag: "qtukey" },
  {
    id: "quade.test",
    href: "/detail/base/quadetest.html",
    texttag: "quade.test",
  },
  { id: "quantile", href: "/detail/base/quantile.html", texttag: "quantile" },
  { id: "quasi", href: "/detail/base/quasi.html", texttag: "quasi" },
  {
    id: "quasibinomial",
    href: "/detail/base/quasibinomial.html",
    texttag: "quasibinomial",
  },
  {
    id: "quasipoisson",
    href: "/detail/base/quasipoisson.html",
    texttag: "quasipoisson",
  },
  { id: "qunif", href: "/detail/base/qunif.html", texttag: "qunif" },
  { id: "qweibull", href: "/detail/base/qweibull.html", texttag: "qweibull" },
  { id: "qwilcox", href: "/detail/base/qwilcox.html", texttag: "qwilcox" },
  { id: "r2dtable", href: "/detail/base/r2dtable.html", texttag: "r2dtable" },
  { id: "rbeta", href: "/detail/base/rbeta.html", texttag: "rbeta" },
  { id: "rbinom", href: "/detail/base/rbinom.html", texttag: "rbinom" },
  { id: "rcauchy", href: "/detail/base/rcauchy.html", texttag: "rcauchy" },
  { id: "rchisq", href: "/detail/base/rchisq.html", texttag: "rchisq" },
  {
    id: "read.ftable",
    href: "/detail/base/readftable.html",
    texttag: "read.ftable",
  },
  {
    id: "rect.hclust",
    href: "/detail/base/recthclust.html",
    texttag: "rect.hclust",
  },
  {
    id: "reformulate",
    href: "/detail/base/reformulate.html",
    texttag: "reformulate",
  },
  { id: "relevel", href: "/detail/base/relevel.html", texttag: "relevel" },
  { id: "reorder", href: "/detail/base/reorder.html", texttag: "reorder" },
  {
    id: "replications",
    href: "/detail/base/replications.html",
    texttag: "replications",
  },
  { id: "reshape", href: "/detail/base/reshape.html", texttag: "reshape" },
  { id: "resid", href: "/detail/base/resid.html", texttag: "resid" },
  {
    id: "residuals",
    href: "/detail/base/residuals.html",
    texttag: "residuals",
  },
  {
    id: "residuals.glm",
    href: "/detail/base/residualsglm.html",
    texttag: "residuals.glm",
  },
  {
    id: "residuals.lm",
    href: "/detail/base/residualslm.html",
    texttag: "residuals.lm",
  },
  { id: "rexp", href: "/detail/base/rexp.html", texttag: "rexp" },
  { id: "rf", href: "/detail/base/rf.html", texttag: "rf" },
  { id: "rgamma", href: "/detail/base/rgamma.html", texttag: "rgamma" },
  { id: "rgeom", href: "/detail/base/rgeom.html", texttag: "rgeom" },
  { id: "rhyper", href: "/detail/base/rhyper.html", texttag: "rhyper" },
  { id: "rlnorm", href: "/detail/base/rlnorm.html", texttag: "rlnorm" },
  { id: "rlogis", href: "/detail/base/rlogis.html", texttag: "rlogis" },
  {
    id: "rmultinom",
    href: "/detail/base/rmultinom.html",
    texttag: "rmultinom",
  },
  { id: "rnbinom", href: "/detail/base/rnbinom.html", texttag: "rnbinom" },
  { id: "rnorm", href: "/detail/base/rnorm.html", texttag: "rnorm" },
  { id: "rpois", href: "/detail/base/rpois.html", texttag: "rpois" },
  {
    id: "rsignrank",
    href: "/detail/base/rsignrank.html",
    texttag: "rsignrank",
  },
  {
    id: "rstandard",
    href: "/detail/base/rstandard.html",
    texttag: "rstandard",
  },
  { id: "rstudent", href: "/detail/base/rstudent.html", texttag: "rstudent" },
  { id: "rt", href: "/detail/base/rt.html", texttag: "rt" },
  { id: "runif", href: "/detail/base/runif.html", texttag: "runif" },
  { id: "runmed", href: "/detail/base/runmed.html", texttag: "runmed" },
  { id: "rweibull", href: "/detail/base/rweibull.html", texttag: "rweibull" },
  { id: "rwilcox", href: "/detail/base/rwilcox.html", texttag: "rwilcox" },
  { id: "rWishart", href: "/detail/base/rWishart.html", texttag: "rWishart" },
  {
    id: "scatter.smooth",
    href: "/detail/base/scattersmooth.html",
    texttag: "scatter.smooth",
  },
  {
    id: "screeplot",
    href: "/detail/base/screeplot.html",
    texttag: "screeplot",
  },
  { id: "sd", href: "/detail/base/sd.html", texttag: "sd" },
  {
    id: "se.contrast",
    href: "/detail/base/secontrast.html",
    texttag: "se.contrast",
  },
  {
    id: "selfStart",
    href: "/detail/base/selfStart.html",
    texttag: "selfStart",
  },
  { id: "setNames", href: "/detail/base/setNames.html", texttag: "setNames" },
  {
    id: "shapiro.test",
    href: "/detail/base/shapirotest.html",
    texttag: "shapiro.test",
  },
  { id: "sigma", href: "/detail/base/sigma.html", texttag: "sigma" },
  { id: "simulate", href: "/detail/base/simulate.html", texttag: "simulate" },
  { id: "smooth", href: "/detail/base/smooth.html", texttag: "smooth" },
  {
    id: "smooth.spline",
    href: "/detail/base/smoothspline.html",
    texttag: "smooth.spline",
  },
  {
    id: "smoothEnds",
    href: "/detail/base/smoothEnds.html",
    texttag: "smoothEnds",
  },
  {
    id: "sortedXyData",
    href: "/detail/base/sortedXyData.html",
    texttag: "sortedXyData",
  },
  { id: "spec.ar", href: "/detail/base/specar.html", texttag: "spec.ar" },
  {
    id: "spec.pgram",
    href: "/detail/base/specpgram.html",
    texttag: "spec.pgram",
  },
  {
    id: "spec.taper",
    href: "/detail/base/spectaper.html",
    texttag: "spec.taper",
  },
  { id: "spectrum", href: "/detail/base/spectrum.html", texttag: "spectrum" },
  { id: "spline", href: "/detail/base/spline.html", texttag: "spline" },
  {
    id: "splinefun",
    href: "/detail/base/splinefun.html",
    texttag: "splinefun",
  },
  {
    id: "splinefunH",
    href: "/detail/base/splinefunH.html",
    texttag: "splinefunH",
  },
  { id: "SSasymp", href: "/detail/base/SSasymp.html", texttag: "SSasymp" },
  {
    id: "SSasympOff",
    href: "/detail/base/SSasympOff.html",
    texttag: "SSasympOff",
  },
  {
    id: "SSasympOrig",
    href: "/detail/base/SSasympOrig.html",
    texttag: "SSasympOrig",
  },
  { id: "SSbiexp", href: "/detail/base/SSbiexp.html", texttag: "SSbiexp" },
  { id: "SSD", href: "/detail/base/SSD.html", texttag: "SSD" },
  { id: "SSfol", href: "/detail/base/SSfol.html", texttag: "SSfol" },
  { id: "SSfpl", href: "/detail/base/SSfpl.html", texttag: "SSfpl" },
  {
    id: "SSgompertz",
    href: "/detail/base/SSgompertz.html",
    texttag: "SSgompertz",
  },
  { id: "SSlogis", href: "/detail/base/SSlogis.html", texttag: "SSlogis" },
  { id: "SSmicmen", href: "/detail/base/SSmicmen.html", texttag: "SSmicmen" },
  {
    id: "SSweibull",
    href: "/detail/base/SSweibull.html",
    texttag: "SSweibull",
  },
  { id: "start", href: "/detail/base/start.html", texttag: "start" },
  {
    id: "stat.anova",
    href: "/detail/base/statanova.html",
    texttag: "stat.anova",
  },
  { id: "step", href: "/detail/base/step.html", texttag: "step" },
  { id: "stepfun", href: "/detail/base/stepfun.html", texttag: "stepfun" },
  { id: "stl", href: "/detail/base/stl.html", texttag: "stl" },
  { id: "StructTS", href: "/detail/base/StructTS.html", texttag: "StructTS" },
  {
    id: "summary.aov",
    href: "/detail/base/summaryaov.html",
    texttag: "summary.aov",
  },
  {
    id: "summary.glm",
    href: "/detail/base/summaryglm.html",
    texttag: "summary.glm",
  },
  {
    id: "summary.lm",
    href: "/detail/base/summarylm.html",
    texttag: "summary.lm",
  },
  {
    id: "summary.manova",
    href: "/detail/base/summarymanova.html",
    texttag: "summary.manova",
  },
  {
    id: "summary.stepfun",
    href: "/detail/base/summarystepfun.html",
    texttag: "summary.stepfun",
  },
  { id: "supsmu", href: "/detail/base/supsmu.html", texttag: "supsmu" },
  { id: "symnum", href: "/detail/base/symnum.html", texttag: "symnum" },
  { id: "t.test", href: "/detail/base/ttest.html", texttag: "t.test" },
  { id: "termplot", href: "/detail/base/termplot.html", texttag: "termplot" },
  { id: "terms", href: "/detail/base/terms.html", texttag: "terms" },
  {
    id: "terms.formula",
    href: "/detail/base/termsformula.html",
    texttag: "terms.formula",
  },
  { id: "time", href: "/detail/base/time.html", texttag: "time" },
  { id: "toeplitz", href: "/detail/base/toeplitz.html", texttag: "toeplitz" },
  { id: "ts", href: "/detail/base/ts.html", texttag: "ts" },
  {
    id: "ts.intersect",
    href: "/detail/base/tsintersect.html",
    texttag: "ts.intersect",
  },
  { id: "ts.plot", href: "/detail/base/tsplot.html", texttag: "ts.plot" },
  { id: "ts.union", href: "/detail/base/tsunion.html", texttag: "ts.union" },
  { id: "tsdiag", href: "/detail/base/tsdiag.html", texttag: "tsdiag" },
  { id: "tsp", href: "/detail/base/tsp.html", texttag: "tsp" },
  { id: "tsp<-", href: "/detail/base/tsp<-.html", texttag: "tsp<-" },
  { id: "tsSmooth", href: "/detail/base/tsSmooth.html", texttag: "tsSmooth" },
  { id: "TukeyHSD", href: "/detail/base/TukeyHSD.html", texttag: "TukeyHSD" },
  { id: "uniroot", href: "/detail/base/uniroot.html", texttag: "uniroot" },
  { id: "update", href: "/detail/base/update.html", texttag: "update" },
  {
    id: "update.default",
    href: "/detail/base/updatedefault.html",
    texttag: "update.default",
  },
  {
    id: "update.formula",
    href: "/detail/base/updateformula.html",
    texttag: "update.formula",
  },
  { id: "var", href: "/detail/base/var.html", texttag: "var" },
  { id: "var.test", href: "/detail/base/vartest.html", texttag: "var.test" },
  {
    id: "variable.names",
    href: "/detail/base/variablenames.html",
    texttag: "variable.names",
  },
  { id: "varimax", href: "/detail/base/varimax.html", texttag: "varimax" },
  { id: "vcov", href: "/detail/base/vcov.html", texttag: "vcov" },
  {
    id: "weighted.mean",
    href: "/detail/base/weightedmean.html",
    texttag: "weighted.mean",
  },
  {
    id: "weighted.residuals",
    href: "/detail/base/weightedresiduals.html",
    texttag: "weighted.residuals",
  },
  { id: "weights", href: "/detail/base/weights.html", texttag: "weights" },
  {
    id: "wilcox.test",
    href: "/detail/base/wilcoxtest.html",
    texttag: "wilcox.test",
  },
  { id: "window", href: "/detail/base/window.html", texttag: "window" },
  { id: "window<-", href: "/detail/base/window<-.html", texttag: "window<-" },
  {
    id: "write.ftable",
    href: "/detail/base/writeftable.html",
    texttag: "write.ftable",
  },
  { id: "xtabs", href: "/detail/base/xtabs.html", texttag: "xtabs" },
];

var infocontent = document.getElementById("baseinfo");
for (let i = 0; i < librarylist.length; i++) {
  const basename = librarylist[i];
  const div = document.createElement("div");
  div.className = "lineitem";
  div.id = basename.id;
  div.style.display = "inline-block";
  div.style.width = "289px";
  div.style.height = "125px";
  div.style.fill = "none";

  const div2 = document.createElement("div");
  div2.className = "basenamebox";
  div2.style.width = "274.045px";
  div2.style.height = "100.124px";
  div2.style.borderRadius = "9.194px";
  div2.style.stroke = "#243D25";
  div2.style.strokeMiterlimit = "10";
  div2.style.strokeWidth = "1";
  div2.style.fontSize = "27px";
  div2.style.border = "1px solid #000";
  div2.style.transform = "translate(21.529px ,57.832px)";

  const atag = document.createElement("a");
  atag.href = basename.href;

  const txttag = document.createElement("text");
  const txtnode = document.createTextNode(basename.texttag);
  txttag.style.fontFamily = "ArialRoundedMTBold";

  txttag.appendChild(txtnode);
  atag.appendChild(txttag);
  div2.appendChild(atag);
  div.appendChild(div2);
  infocontent.appendChild(div);
}
