const librarylist = [
  { id: ".Call", href: "/detail/base/Call.html", texttag: ".Call" },
  { id: ".Device", href: "/detail/base/Device.html", texttag: ".Device" },
  { id: ".Internal", href: "/detail/base/Internal.html", texttag: ".Internal" },
  {
    id: ".Last.value",
    href: "/detail/base/Last.value.html",
    texttag: ".Last.value",
  },
  { id: ".Library", href: "/detail/base/Library.html", texttag: ".Library" },
  { id: ".Machine", href: "/detail/base/Machine.html", texttag: ".Machine" },
  { id: ".Platform", href: "/detail/base/Platform.html", texttag: ".Platform" },
  {
    id: ".Primitive",
    href: "/detail/base/Primitive.html",
    texttag: ".Primitive",
  },
  { id: ".S3method", href: "/detail/base/S3method.html", texttag: ".S3method" },
  { id: ".bincode", href: "/detail/base/bincode.html", texttag: ".bincode" },
  {
    id: ".deparseOpts",
    href: "/detail/base/deparseOpts.html",
    texttag: ".deparseOpts",
  },
  { id: ".onLoad", href: "/detail/base/onLoad.html", texttag: ".onLoad" },
  { id: ".packages", href: "/detail/base/packages.html", texttag: ".packages" },
  {
    id: ".standard_regexps",
    href: "/detail/base/standard_regexps.html",
    texttag: ".standard_regexps",
  },
  { id: ":", href: "/detail/base/:.html", texttag: ":" },
  { id: "::", href: "/detail/base/::.html", texttag: "::" },
  { id: "@", href: "/detail/base/@.html", texttag: "@" },
  {
    id: "Arithmetic",
    href: "/detail/base/Arithmetic.html",
    texttag: "Arithmetic",
  },
  { id: "AsIs", href: "/detail/base/AsIs.html", texttag: "AsIs" },
  { id: "Bessel", href: "/detail/base/Bessel.html", texttag: "Bessel" },
  {
    id: "Comparison",
    href: "/detail/base/Comparison.html",
    texttag: "Comparison",
  },
  {
    id: "Constants",
    href: "/detail/base/Constants.html",
    texttag: "Constants",
  },
  { id: "Control", href: "/detail/base/Control.html", texttag: "Control" },
  {
    id: "Cstack_info",
    href: "/detail/base/Cstack_info.html",
    texttag: "Cstack_info",
  },
  {
    id: "DateTimeClasses",
    href: "/detail/base/DateTimeClasses.html",
    texttag: "DateTimeClasses",
  },
  { id: "Dates", href: "/detail/base/Dates.html", texttag: "Dates" },
  { id: "Defunct", href: "/detail/base/Defunct.html", texttag: "Defunct" },
  {
    id: "Deprecated",
    href: "/detail/base/Deprecated.html",
    texttag: "Deprecated",
  },
  { id: "Encoding", href: "/detail/base/Encoding.html", texttag: "Encoding" },
  {
    id: "Character",
    href: "/detail/base/Character.html",
    texttag: "Character",
  },
  { id: "Extract", href: "/detail/base/Extract.html", texttag: "Extract" },
  { id: "Filter", href: "/detail/base/Filter.html", texttag: "Filter" },
  {
    id: "Programming",
    href: "/detail/base/Programming.html",
    texttag: "Programming",
  },
  { id: "Foreign", href: "/detail/base/Foreign.html", texttag: "Foreign" },
  {
    id: "ISOdatetime",
    href: "/detail/base/ISOdatetime.html",
    texttag: "ISOdatetime",
  },
  {
    id: "Representations",
    href: "/detail/base/Representations.html",
    texttag: "Representations",
  },
  {
    id: "InternalMethods",
    href: "/detail/base/InternalMethods.html",
    texttag: "InternalMethods",
  },
  {
    id: "La_library",
    href: "/detail/base/La_library.html",
    texttag: "La_library",
  },
  {
    id: "La_version",
    href: "/detail/base/La_version.html",
    texttag: "La_version",
  },
  { id: "Logic", href: "/detail/base/Logic.html", texttag: "Logic" },
  { id: "Memory", href: "/detail/base/Memory.html", texttag: "Memory" },
  {
    id: "Memory-limits",
    href: "/detail/base/Memory-limits.html",
    texttag: "Memory-limits",
  },
  { id: "NA", href: "/detail/base/NA.html", texttag: "NA" },
  { id: "NULL", href: "/detail/base/NULL.html", texttag: "NULL" },
  {
    id: "NotYetImplemented",
    href: "/detail/base/NotYetImplemented.html",
    texttag: "NotYetImplemented",
  },
  {
    id: "Arguments",
    href: "/detail/base/Arguments.html",
    texttag: "Arguments",
  },
  {
    id: "NumericConstants",
    href: "/detail/base/NumericConstants.html",
    texttag: "NumericConstants",
  },
  { id: "Ops.Date", href: "/detail/base/OpsDate.html", texttag: "Ops.Date" },
  { id: "Paren", href: "/detail/base/Paren.html", texttag: "Paren" },
  { id: "Quotes", href: "/detail/base/Quotes.html", texttag: "Quotes" },
  { id: "R.Version", href: "/detail/base/RVersion.html", texttag: "R.Version" },
  { id: "R.home", href: "/detail/base/Rhome.html", texttag: "R.home" },
  { id: "Random", href: "/detail/base/Random.html", texttag: "Random" },
  {
    id: "Random.user",
    href: "/detail/base/Randomuser.html",
    texttag: "Random.user",
  },
  { id: "Rdconv", href: "/detail/base/Rdconv.html", texttag: "Rdconv" },
  { id: "Recall", href: "/detail/base/Recall.html", texttag: "Recall" },
  { id: "Reserved", href: "/detail/base/Reserved.html", texttag: "Reserved" },
  { id: "Signals", href: "/detail/base/Signals.html", texttag: "Signals" },
  { id: "Special", href: "/detail/base/Special.html", texttag: "Special" },
  {
    id: "StackOverflows",
    href: "/detail/base/StackOverflows.html",
    texttag: "StackOverflows",
  },
  { id: "Startup", href: "/detail/base/Startup.html", texttag: "Startup" },
  { id: "Syntax", href: "/detail/base/Syntax.html", texttag: "Syntax" },
  {
    id: "Sys.getenv",
    href: "/detail/base/Sysgetenv.html",
    texttag: "Sys.getenv",
  },
  {
    id: "Sys.getpid",
    href: "/detail/base/Sysgetpid.html",
    texttag: "Sys.getpid",
  },
  { id: "Sys.glob", href: "/detail/base/Sysglob.html", texttag: "Sys.glob" },
  { id: "Sys.info", href: "/detail/base/Sysinfo.html", texttag: "Sys.info" },
  {
    id: "Sys.localeconv",
    href: "/detail/base/Syslocaleconv.html",
    texttag: "Sys.localeconv",
  },
  {
    id: "Representations",
    href: "/detail/base/Representations.html",
    texttag: "Representations",
  },
  {
    id: "Sys.readlink",
    href: "/detail/base/Sysreadlink.html",
    texttag: "Sys.readlink",
  },
  {
    id: "Sys.setFileTime",
    href: "/detail/base/SyssetFileTime.html",
    texttag: "Sys.setFileTime",
  },
  {
    id: "Sys.setenv",
    href: "/detail/base/Syssetenv.html",
    texttag: "Sys.setenv",
  },
  { id: "Sys.sleep", href: "/detail/base/Syssleep.html", texttag: "Sys.sleep" },
  { id: "Sys.time", href: "/detail/base/Systime.html", texttag: "Sys.time" },
  { id: "Sys.which", href: "/detail/base/Syswhich.html", texttag: "Sys.which" },
  { id: "Trig", href: "/detail/base/Trig.html", texttag: "Trig" },
  {
    id: "UseMethod",
    href: "/detail/base/UseMethod.html",
    texttag: "UseMethod",
  },
  {
    id: "Vectorize",
    href: "/detail/base/Vectorize.html",
    texttag: "Vectorize",
  },
  {
    id: "[.data.frame",
    href: "/detail/base/[data.frame.html",
    texttag: "[.data.frame",
  },
  { id: "[.factor", href: "/detail/base/[factor.html", texttag: "[.factor" },
  {
    id: "abbreviate",
    href: "/detail/base/abbreviate.html",
    texttag: "abbreviate",
  },
  { id: "abs", href: "/detail/base/abs.html", texttag: "abs" },
  {
    id: "addTaskCallback",
    href: "/detail/base/addTaskCallback.html",
    texttag: "addTaskCallback",
  },
  { id: "agrep", href: "/detail/base/agrep.html", texttag: "agrep" },
  { id: "all", href: "/detail/base/all.html", texttag: "all" },
  { id: "all.equal", href: "/detail/base/allequal.html", texttag: "all.equal" },
  { id: "all.names", href: "/detail/base/allnames.html", texttag: "all.names" },
  { id: "any", href: "/detail/base/any.html", texttag: "any" },
  { id: "aperm", href: "/detail/base/aperm.html", texttag: "aperm" },
  { id: "append", href: "/detail/base/append.html", texttag: "append" },
  { id: "apply", href: "/detail/base/apply.html", texttag: "apply" },
  { id: "args", href: "/detail/base/args.html", texttag: "args" },
  { id: "array", href: "/detail/base/array.html", texttag: "array" },
  { id: "as.Date", href: "/detail/base/asDate.html", texttag: "as.Date" },
  {
    id: "as.POSIXct",
    href: "/detail/base/asPOSIXct.html",
    texttag: "as.POSIXct",
  },
  {
    id: "as.data.frame",
    href: "/detail/base/asdata.frame.html",
    texttag: "as.data.frame",
  },
  {
    id: "as.environment",
    href: "/detail/base/asenvironment.html",
    texttag: "as.environment",
  },
  {
    id: "as.function",
    href: "/detail/base/asfunction.html",
    texttag: "as.function",
  },
  { id: "asplit", href: "/detail/base/asplit.html", texttag: "asplit" },
  { id: "assign", href: "/detail/base/assign.html", texttag: "assign" },
  {
    id: "assignOps",
    href: "/detail/base/assignOps.html",
    texttag: "assignOps",
  },
  { id: "attach", href: "/detail/base/attach.html", texttag: "attach" },
  {
    id: "attachNamespace",
    href: "/detail/base/attachNamespace.html",
    texttag: "attachNamespace",
  },
  { id: "attr", href: "/detail/base/attr.html", texttag: "attr" },
  {
    id: "attributes",
    href: "/detail/base/attributes.html",
    texttag: "attributes",
  },
  { id: "autoload", href: "/detail/base/autoload.html", texttag: "autoload" },
  {
    id: "backsolve",
    href: "/detail/base/backsolve.html",
    texttag: "backsolve",
  },
  {
    id: "base-package",
    href: "/detail/base/base-package.html",
    texttag: "base-package",
  },
  { id: "basename", href: "/detail/base/basename.html", texttag: "basename" },
  { id: "bindenv", href: "/detail/base/bindenv.html", texttag: "bindenv" },
  { id: "Bindings", href: "/detail/base/Bindings.html", texttag: "Bindings" },
  { id: "bitwNot", href: "/detail/base/bitwNot.html", texttag: "bitwNot" },
  { id: "body", href: "/detail/base/body.html", texttag: "body" },
  { id: "Function", href: "/detail/base/Function.html", texttag: "Function" },
  { id: "bquote", href: "/detail/base/bquote.html", texttag: "bquote" },
  { id: "browser", href: "/detail/base/browser.html", texttag: "browser" },
  {
    id: "browserText",
    href: "/detail/base/browserText.html",
    texttag: "browserText",
  },
  { id: "to", href: "/detail/base/to.html", texttag: "to" },
  { id: "builtins", href: "/detail/base/builtins.html", texttag: "builtins" },
  { id: "by", href: "/detail/base/by.html", texttag: "by" },
  { id: "Factors", href: "/detail/base/Factors.html", texttag: "Factors" },
  { id: "c", href: "/detail/base/c.html", texttag: "c" },
  { id: "call", href: "/detail/base/call.html", texttag: "call" },
  { id: "callCC", href: "/detail/base/callCC.html", texttag: "callCC" },
  {
    id: "capabilities",
    href: "/detail/base/capabilities.html",
    texttag: "capabilities",
  },
  { id: "cat", href: "/detail/base/cat.html", texttag: "cat" },
  { id: "cbind", href: "/detail/base/cbind.html", texttag: "cbind" },
  { id: "ceiling", href: "/detail/base/ceiling.html", texttag: "ceiling" },
  {
    id: "char.expand",
    href: "/detail/base/charexpand.html",
    texttag: "char.expand",
  },
  {
    id: "charToRaw",
    href: "/detail/base/charToRaw.html",
    texttag: "charToRaw",
  },
  {
    id: "character",
    href: "/detail/base/character.html",
    texttag: "character",
  },
  {
    id: "charmatch",
    href: "/detail/base/charmatch.html",
    texttag: "charmatch",
  },
  { id: "chartr", href: "/detail/base/chartr.html", texttag: "chartr" },
  { id: "chkDots", href: "/detail/base/chkDots.html", texttag: "chkDots" },
  { id: "Its", href: "/detail/base/Its.html", texttag: "Its" },
  { id: "chol", href: "/detail/base/chol.html", texttag: "chol" },
  { id: "chol2inv", href: "/detail/base/chol2inv.html", texttag: "chol2inv" },
  { id: "class", href: "/detail/base/class.html", texttag: "class" },
  { id: "col", href: "/detail/base/col.html", texttag: "col" },
  { id: "colSums", href: "/detail/base/colSums.html", texttag: "colSums" },
  {
    id: "commandArgs",
    href: "/detail/base/commandArgs.html",
    texttag: "commandArgs",
  },
  { id: "comment", href: "/detail/base/comment.html", texttag: "comment" },
  { id: "complex", href: "/detail/base/complex.html", texttag: "complex" },
  {
    id: "conditions",
    href: "/detail/base/conditions.html",
    texttag: "conditions",
  },
  {
    id: "conflicts",
    href: "/detail/base/conflicts.html",
    texttag: "conflicts",
  },
  {
    id: "connections",
    href: "/detail/base/connections.html",
    texttag: "connections",
  },
  { id: "URLs,", href: "/detail/base/URLs,.html", texttag: "URLs," },
  {
    id: "contributors",
    href: "/detail/base/contributors.html",
    texttag: "contributors",
  },
  {
    id: "copyright",
    href: "/detail/base/copyright.html",
    texttag: "copyright",
  },
  { id: "cosh", href: "/detail/base/cosh.html", texttag: "cosh" },
  {
    id: "crossprod",
    href: "/detail/base/crossprod.html",
    texttag: "crossprod",
  },
  { id: "cumsum", href: "/detail/base/cumsum.html", texttag: "cumsum" },
  {
    id: "curlGetHeaders",
    href: "/detail/base/curlGetHeaders.html",
    texttag: "curlGetHeaders",
  },
  { id: "cut", href: "/detail/base/cut.html", texttag: "cut" },
  {
    id: "cut.POSIXt",
    href: "/detail/base/cutPOSIXt.html",
    texttag: "cut.POSIXt",
  },
  {
    id: "data.class",
    href: "/detail/base/dataclass.html",
    texttag: "data.class",
  },
  {
    id: "data.frame",
    href: "/detail/base/dataframe.html",
    texttag: "data.frame",
  },
  {
    id: "data.matrix",
    href: "/detail/base/datamatrix.html",
    texttag: "data.matrix",
  },
  { id: "date", href: "/detail/base/date.html", texttag: "date" },
  { id: "debug", href: "/detail/base/debug.html", texttag: "debug" },
  {
    id: "delayedAssign",
    href: "/detail/base/delayedAssign.html",
    texttag: "delayedAssign",
  },
  { id: "deparse", href: "/detail/base/deparse.html", texttag: "deparse" },
  { id: "det", href: "/detail/base/det.html", texttag: "det" },
  { id: "detach", href: "/detail/base/detach.html", texttag: "detach" },
  { id: "diag", href: "/detail/base/diag.html", texttag: "diag" },
  { id: "diff", href: "/detail/base/diff.html", texttag: "diff" },
  { id: "difftime", href: "/detail/base/difftime.html", texttag: "difftime" },
  { id: "dim", href: "/detail/base/dim.html", texttag: "dim" },
  { id: "dimnames", href: "/detail/base/dimnames.html", texttag: "dimnames" },
  {
    id: "dir.create",
    href: "/detail/base/dircreate.html",
    texttag: "dir.create",
  },
  {
    id: "Permissions",
    href: "/detail/base/Permissions.html",
    texttag: "Permissions",
  },
  { id: "do.call", href: "/detail/base/docall.html", texttag: "do.call" },
  {
    id: "dontCheck",
    href: "/detail/base/dontCheck.html",
    texttag: "dontCheck",
  },
  { id: "dots", href: "/detail/base/dots.html", texttag: "dots" },
  { id: "double", href: "/detail/base/double.html", texttag: "double" },
  { id: "dput", href: "/detail/base/dput.html", texttag: "dput" },
  { id: "drop", href: "/detail/base/drop.html", texttag: "drop" },
  {
    id: "droplevels",
    href: "/detail/base/droplevels.html",
    texttag: "droplevels",
  },
  { id: "dump", href: "/detail/base/dump.html", texttag: "dump" },
  {
    id: "duplicated",
    href: "/detail/base/duplicated.html",
    texttag: "duplicated",
  },
  { id: "dyn.load", href: "/detail/base/dynload.html", texttag: "dyn.load" },
  { id: "eapply", href: "/detail/base/eapply.html", texttag: "eapply" },
  { id: "eigen", href: "/detail/base/eigen.html", texttag: "eigen" },
  {
    id: "encodeString",
    href: "/detail/base/encodeString.html",
    texttag: "encodeString",
  },
  {
    id: "environment",
    href: "/detail/base/environment.html",
    texttag: "environment",
  },
  {
    id: "environment",
    href: "/detail/base/environment.html",
    texttag: "environment",
  },
  { id: "eval", href: "/detail/base/eval.html", texttag: "eval" },
  { id: "exists", href: "/detail/base/exists.html", texttag: "exists" },
  {
    id: "expand.grid",
    href: "/detail/base/expandgrid.html",
    texttag: "expand.grid",
  },
  { id: "Factor", href: "/detail/base/Factor.html", texttag: "Factor" },
  {
    id: "expression",
    href: "/detail/base/expression.html",
    texttag: "expression",
  },
  {
    id: "extSoftVersion",
    href: "/detail/base/extSoftVersion.html",
    texttag: "extSoftVersion",
  },
  { id: "factor", href: "/detail/base/factor.html", texttag: "factor" },
  { id: "file", href: "/detail/base/file.html", texttag: "file" },
  {
    id: "file.access",
    href: "/detail/base/fileaccess.html",
    texttag: "file.access",
  },
  {
    id: "file.choose",
    href: "/detail/base/filechoose.html",
    texttag: "file.choose",
  },
  { id: "file.info", href: "/detail/base/fileinfo.html", texttag: "file.info" },
  { id: "file.path", href: "/detail/base/filepath.html", texttag: "file.path" },
  { id: "file.show", href: "/detail/base/fileshow.html", texttag: "file.show" },
  { id: "files", href: "/detail/base/files.html", texttag: "files" },
  {
    id: "find.package",
    href: "/detail/base/findpackage.html",
    texttag: "find.package",
  },
  {
    id: "findInterval",
    href: "/detail/base/findInterval.html",
    texttag: "findInterval",
  },
  { id: "force", href: "/detail/base/force.html", texttag: "force" },
  {
    id: "forceAndCall",
    href: "/detail/base/forceAndCall.html",
    texttag: "forceAndCall",
  },
  { id: "formals", href: "/detail/base/formals.html", texttag: "formals" },
  {
    id: "Arguments",
    href: "/detail/base/Arguments.html",
    texttag: "Arguments",
  },
  { id: "format", href: "/detail/base/format.html", texttag: "format" },
  {
    id: "format.info",
    href: "/detail/base/formatinfo.html",
    texttag: "format.info",
  },
  {
    id: "format.pval",
    href: "/detail/base/formatpval.html",
    texttag: "format.pval",
  },
  { id: "formatC", href: "/detail/base/formatC.html", texttag: "formatC" },
  { id: "formatDL", href: "/detail/base/formatDL.html", texttag: "formatDL" },
  { id: "function", href: "/detail/base/function.html", texttag: "function" },
  { id: "gc", href: "/detail/base/gc.html", texttag: "gc" },
  { id: "gc.time", href: "/detail/base/gctime.html", texttag: "gc.time" },
  {
    id: "gctorture",
    href: "/detail/base/gctorture.html",
    texttag: "gctorture",
  },
  { id: "get", href: "/detail/base/get.html", texttag: "get" },
  {
    id: "getDLLRegisteredRoutines",
    href: "/detail/base/getDLLRegisteredRoutines.html",
    texttag: "getDLLRegisteredRoutines",
  },
  {
    id: "Reflectance",
    href: "/detail/base/Reflectance.html",
    texttag: "Reflectance",
  },
  { id: "in", href: "/detail/base/in.html", texttag: "in" },
  { id: "getHook", href: "/detail/base/getHook.html", texttag: "getHook" },
  { id: "Attach,", href: "/detail/base/Attach,.html", texttag: "Attach," },
  {
    id: "getLoadedDLLs",
    href: "/detail/base/getLoadedDLLs.html",
    texttag: "getLoadedDLLs",
  },
  {
    id: "getNativeSymbolInfo",
    href: "/detail/base/getNativeSymbolInfo.html",
    texttag: "getNativeSymbolInfo",
  },
  {
    id: "(C/Fortran)",
    href: "/detail/base/(C/Fortran).html",
    texttag: "(C/Fortran)",
  },
  {
    id: "getTaskCallbackNames",
    href: "/detail/base/getTaskCallbackNames.html",
    texttag: "getTaskCallbackNames",
  },
  {
    id: "Top-Level",
    href: "/detail/base/Top-Level.html",
    texttag: "Top-Level",
  },
  { id: "gettext", href: "/detail/base/gettext.html", texttag: "gettext" },
  { id: "getwd", href: "/detail/base/getwd.html", texttag: "getwd" },
  { id: "gl", href: "/detail/base/gl.html", texttag: "gl" },
  { id: "grep", href: "/detail/base/grep.html", texttag: "grep" },
  { id: "grepRaw", href: "/detail/base/grepRaw.html", texttag: "grepRaw" },
  {
    id: "groupGeneric",
    href: "/detail/base/groupGeneric.html",
    texttag: "groupGeneric",
  },
  { id: "grouping", href: "/detail/base/grouping.html", texttag: "grouping" },
  { id: "gzcon", href: "/detail/base/gzcon.html", texttag: "gzcon" },
  { id: "hexmode", href: "/detail/base/hexmode.html", texttag: "hexmode" },
  { id: "iconv", href: "/detail/base/iconv.html", texttag: "iconv" },
  {
    id: "icuSetCollate",
    href: "/detail/base/icuSetCollate.html",
    texttag: "icuSetCollate",
  },
  {
    id: "identical",
    href: "/detail/base/identical.html",
    texttag: "identical",
  },
  { id: "identity", href: "/detail/base/identity.html", texttag: "identity" },
  { id: "ifelse", href: "/detail/base/ifelse.html", texttag: "ifelse" },
  { id: "integer", href: "/detail/base/integer.html", texttag: "integer" },
  {
    id: "interaction",
    href: "/detail/base/interaction.html",
    texttag: "interaction",
  },
  {
    id: "interactive",
    href: "/detail/base/interactive.html",
    texttag: "interactive",
  },
  {
    id: "invisible",
    href: "/detail/base/invisible.html",
    texttag: "invisible",
  },
  { id: "is.R", href: "/detail/base/isR.html", texttag: "is.R" },
  { id: "is.finite", href: "/detail/base/isfinite.html", texttag: "is.finite" },
  {
    id: "is.function",
    href: "/detail/base/isfunction.html",
    texttag: "is.function",
  },
  {
    id: "is.language",
    href: "/detail/base/islanguage.html",
    texttag: "is.language",
  },
  { id: "is.object", href: "/detail/base/isobject.html", texttag: "is.object" },
  {
    id: "is.recursive",
    href: "/detail/base/isrecursive.html",
    texttag: "is.recursive",
  },
  { id: "is.single", href: "/detail/base/issingle.html", texttag: "is.single" },
  {
    id: "is.unsorted",
    href: "/detail/base/isunsorted.html",
    texttag: "is.unsorted",
  },
  { id: "isS4", href: "/detail/base/isS4.html", texttag: "isS4" },
  {
    id: "isSymmetric",
    href: "/detail/base/isSymmetric.html",
    texttag: "isSymmetric",
  },
  {
    id: "(Hermitian)",
    href: "/detail/base/(Hermitian).html",
    texttag: "(Hermitian)",
  },
  { id: "jitter", href: "/detail/base/jitter.html", texttag: "jitter" },
  { id: "kappa", href: "/detail/base/kappa.html", texttag: "kappa" },
  { id: "Matrix", href: "/detail/base/Matrix.html", texttag: "Matrix" },
  {
    id: "kronecker",
    href: "/detail/base/kronecker.html",
    texttag: "kronecker",
  },
  {
    id: "l10n_info",
    href: "/detail/base/l10n_info.html",
    texttag: "l10n_info",
  },
  { id: "labels", href: "/detail/base/labels.html", texttag: "labels" },
  { id: "lapply", href: "/detail/base/lapply.html", texttag: "lapply" },
  { id: "length", href: "/detail/base/length.html", texttag: "length" },
  { id: "lengths", href: "/detail/base/lengths.html", texttag: "lengths" },
  { id: "levels", href: "/detail/base/levels.html", texttag: "levels" },
  {
    id: "libcurlVersion",
    href: "/detail/base/libcurlVersion.html",
    texttag: "libcurlVersion",
  },
  { id: "library", href: "/detail/base/library.html", texttag: "library" },
  {
    id: "library.dynam",
    href: "/detail/base/librarydynam.html",
    texttag: "library.dynam",
  },
  { id: "license", href: "/detail/base/license.html", texttag: "license" },
  { id: "list", href: "/detail/base/list.html", texttag: "list" },
  {
    id: "list.files",
    href: "/detail/base/listfiles.html",
    texttag: "list.files",
  },
  { id: "list2DF", href: "/detail/base/list2DF.html", texttag: "list2DF" },
  { id: "list2env", href: "/detail/base/list2env.html", texttag: "list2env" },
  { id: "load", href: "/detail/base/load.html", texttag: "load" },
  { id: "locales", href: "/detail/base/locales.html", texttag: "locales" },
  { id: "log", href: "/detail/base/log.html", texttag: "log" },
  { id: "logical", href: "/detail/base/logical.html", texttag: "logical" },
  { id: "long", href: "/detail/base/long.html", texttag: "long" },
  { id: "lower.tri", href: "/detail/base/lowertri.html", texttag: "lower.tri" },
  { id: "ls", href: "/detail/base/ls.html", texttag: "ls" },
  {
    id: "make.names",
    href: "/detail/base/makenames.html",
    texttag: "make.names",
  },
  {
    id: "make.unique",
    href: "/detail/base/makeunique.html",
    texttag: "make.unique",
  },
  { id: "mapply", href: "/detail/base/mapply.html", texttag: "mapply" },
  {
    id: "Arguments",
    href: "/detail/base/Arguments.html",
    texttag: "Arguments",
  },
  {
    id: "marginSums",
    href: "/detail/base/marginSums.html",
    texttag: "marginSums",
  },
  {
    id: "mat.or.vec",
    href: "/detail/base/mator.vec.html",
    texttag: "mat.or.vec",
  },
  { id: "match", href: "/detail/base/match.html", texttag: "match" },
  { id: "match.arg", href: "/detail/base/matcharg.html", texttag: "match.arg" },
  {
    id: "match.call",
    href: "/detail/base/matchcall.html",
    texttag: "match.call",
  },
  { id: "match.fun", href: "/detail/base/matchfun.html", texttag: "match.fun" },
  { id: "matmult", href: "/detail/base/matmult.html", texttag: "matmult" },
  { id: "matrix", href: "/detail/base/matrix.html", texttag: "matrix" },
  { id: "max", href: "/detail/base/max.html", texttag: "max" },
  { id: "max.col", href: "/detail/base/maxcol.html", texttag: "max.col" },
  { id: "mean", href: "/detail/base/mean.html", texttag: "mean" },
  {
    id: "mem.maxVSize",
    href: "/detail/base/memmaxVSize.html",
    texttag: "mem.maxVSize",
  },
  {
    id: "memCompress",
    href: "/detail/base/memCompress.html",
    texttag: "memCompress",
  },
  {
    id: "memory.profile",
    href: "/detail/base/memoryprofile.html",
    texttag: "memory.profile",
  },
  { id: "merge", href: "/detail/base/merge.html", texttag: "merge" },
  { id: "message", href: "/detail/base/message.html", texttag: "message" },
  { id: "missing", href: "/detail/base/missing.html", texttag: "missing" },
  { id: "mode", href: "/detail/base/mode.html", texttag: "mode" },
  { id: "mtfrm", href: "/detail/base/mtfrm.html", texttag: "mtfrm" },
  { id: "name", href: "/detail/base/name.html", texttag: "name" },
  { id: "names", href: "/detail/base/names.html", texttag: "names" },
  { id: "nargs", href: "/detail/base/nargs.html", texttag: "nargs" },
  { id: "nchar", href: "/detail/base/nchar.html", texttag: "nchar" },
  { id: "Width)", href: "/detail/base/Width).html", texttag: "Width)" },
  { id: "nlevels", href: "/detail/base/nlevels.html", texttag: "nlevels" },
  { id: "noquote", href: "/detail/base/noquote.html", texttag: "noquote" },
  { id: "Strings", href: "/detail/base/Strings.html", texttag: "Strings" },
  { id: "norm", href: "/detail/base/norm.html", texttag: "norm" },
  {
    id: "normalizePath",
    href: "/detail/base/normalizePath.html",
    texttag: "normalizePath",
  },
  { id: "nrow", href: "/detail/base/nrow.html", texttag: "nrow" },
  { id: "numeric", href: "/detail/base/numeric.html", texttag: "numeric" },
  {
    id: "numeric_version",
    href: "/detail/base/numeric_version.html",
    texttag: "numeric_version",
  },
  { id: "octmode", href: "/detail/base/octmode.html", texttag: "octmode" },
  { id: "on.exit", href: "/detail/base/onexit.html", texttag: "on.exit" },
  { id: "options", href: "/detail/base/options.html", texttag: "options" },
  { id: "order", href: "/detail/base/order.html", texttag: "order" },
  { id: "outer", href: "/detail/base/outer.html", texttag: "outer" },
  { id: "parse", href: "/detail/base/parse.html", texttag: "parse" },
  { id: "paste", href: "/detail/base/paste.html", texttag: "paste" },
  {
    id: "path.expand",
    href: "/detail/base/pathexpand.html",
    texttag: "path.expand",
  },
  {
    id: "pcre_config",
    href: "/detail/base/pcre_config.html",
    texttag: "pcre_config",
  },
  { id: "pipeOp", href: "/detail/base/pipeOp.html", texttag: "pipeOp" },
  { id: "plot", href: "/detail/base/plot.html", texttag: "plot" },
  { id: "pmatch", href: "/detail/base/pmatch.html", texttag: "pmatch" },
  { id: "polyroot", href: "/detail/base/polyroot.html", texttag: "polyroot" },
  {
    id: "pos.to.env",
    href: "/detail/base/posto.env.html",
    texttag: "pos.to.env",
  },
  {
    id: "Environments",
    href: "/detail/base/Environments.html",
    texttag: "Environments",
  },
  { id: "pretty", href: "/detail/base/pretty.html", texttag: "pretty" },
  { id: "print", href: "/detail/base/print.html", texttag: "print" },
  {
    id: "print.data.frame",
    href: "/detail/base/printdata.frame.html",
    texttag: "print.data.frame",
  },
  {
    id: "print.default",
    href: "/detail/base/printdefault.html",
    texttag: "print.default",
  },
  { id: "prmatrix", href: "/detail/base/prmatrix.html", texttag: "prmatrix" },
  { id: "proc.time", href: "/detail/base/proctime.html", texttag: "proc.time" },
  { id: "prod", href: "/detail/base/prod.html", texttag: "prod" },
  {
    id: "proportions",
    href: "/detail/base/proportions.html",
    texttag: "proportions",
  },
  { id: "Table", href: "/detail/base/Table.html", texttag: "Table" },
  { id: "pushBack", href: "/detail/base/pushBack.html", texttag: "pushBack" },
  { id: "qr", href: "/detail/base/qr.html", texttag: "qr" },
  { id: "qr.X", href: "/detail/base/qrX.html", texttag: "qr.X" },
  { id: "Object", href: "/detail/base/Object.html", texttag: "Object" },
  { id: "quit", href: "/detail/base/quit.html", texttag: "quit" },
  { id: "range", href: "/detail/base/range.html", texttag: "range" },
  { id: "rank", href: "/detail/base/rank.html", texttag: "rank" },
  { id: "rapply", href: "/detail/base/rapply.html", texttag: "rapply" },
  { id: "raw", href: "/detail/base/raw.html", texttag: "raw" },
  {
    id: "rawConnection",
    href: "/detail/base/rawConnection.html",
    texttag: "rawConnection",
  },
  { id: "read.dcf", href: "/detail/base/readdcf.html", texttag: "read.dcf" },
  { id: "readBin", href: "/detail/base/readBin.html", texttag: "readBin" },
  { id: "readChar", href: "/detail/base/readChar.html", texttag: "readChar" },
  {
    id: "Connections",
    href: "/detail/base/Connections.html",
    texttag: "Connections",
  },
  {
    id: "readLines",
    href: "/detail/base/readLines.html",
    texttag: "readLines",
  },
  { id: "readRDS", href: "/detail/base/readRDS.html", texttag: "readRDS" },
  {
    id: "readRenviron",
    href: "/detail/base/readRenviron.html",
    texttag: "readRenviron",
  },
  { id: "readline", href: "/detail/base/readline.html", texttag: "readline" },
  {
    id: "reg.finalizer",
    href: "/detail/base/regfinalizer.html",
    texttag: "reg.finalizer",
  },
  { id: "regex", href: "/detail/base/regex.html", texttag: "regex" },
  {
    id: "regmatches",
    href: "/detail/base/regmatches.html",
    texttag: "regmatches",
  },
  { id: "remove", href: "/detail/base/remove.html", texttag: "remove" },
  { id: "rep", href: "/detail/base/rep.html", texttag: "rep" },
  { id: "replace", href: "/detail/base/replace.html", texttag: "replace" },
  { id: "rev", href: "/detail/base/rev.html", texttag: "rev" },
  { id: "rle", href: "/detail/base/rle.html", texttag: "rle" },
  {
    id: "round.POSIXt",
    href: "/detail/base/roundPOSIXt.html",
    texttag: "round.POSIXt",
  },
  { id: "row", href: "/detail/base/row.html", texttag: "row" },
  { id: "row.names", href: "/detail/base/rownames.html", texttag: "row.names" },
  { id: "rownames", href: "/detail/base/rownames.html", texttag: "rownames" },
  { id: "rowsum", href: "/detail/base/rowsum.html", texttag: "rowsum" },
  { id: "Based", href: "/detail/base/Based.html", texttag: "Based" },
  { id: "sQuote", href: "/detail/base/sQuote.html", texttag: "sQuote" },
  { id: "sample", href: "/detail/base/sample.html", texttag: "sample" },
  { id: "save", href: "/detail/base/save.html", texttag: "save" },
  { id: "scale", href: "/detail/base/scale.html", texttag: "scale" },
  { id: "scan", href: "/detail/base/scan.html", texttag: "scan" },
  { id: "search", href: "/detail/base/search.html", texttag: "search" },
  { id: "seek", href: "/detail/base/seek.html", texttag: "seek" },
  { id: "seq", href: "/detail/base/seq.html", texttag: "seq" },
  { id: "seq.Date", href: "/detail/base/seqDate.html", texttag: "seq.Date" },
  {
    id: "seq.POSIXt",
    href: "/detail/base/seqPOSIXt.html",
    texttag: "seq.POSIXt",
  },
  { id: "sequence", href: "/detail/base/sequence.html", texttag: "sequence" },
  {
    id: "serialize",
    href: "/detail/base/serialize.html",
    texttag: "serialize",
  },
  {
    id: "setTimeLimit",
    href: "/detail/base/setTimeLimit.html",
    texttag: "setTimeLimit",
  },
  { id: "shQuote", href: "/detail/base/shQuote.html", texttag: "shQuote" },
  {
    id: "showConnections",
    href: "/detail/base/showConnections.html",
    texttag: "showConnections",
  },
  { id: "sign", href: "/detail/base/sign.html", texttag: "sign" },
  { id: "sink", href: "/detail/base/sink.html", texttag: "sink" },
  {
    id: "slice.index",
    href: "/detail/base/sliceindex.html",
    texttag: "slice.index",
  },
  {
    id: "socketSelect",
    href: "/detail/base/socketSelect.html",
    texttag: "socketSelect",
  },
  { id: "solve", href: "/detail/base/solve.html", texttag: "solve" },
  { id: "sort", href: "/detail/base/sort.html", texttag: "sort" },
  { id: "source", href: "/detail/base/source.html", texttag: "source" },
  {
    id: "Expressions",
    href: "/detail/base/Expressions.html",
    texttag: "Expressions",
  },
  { id: "split", href: "/detail/base/split.html", texttag: "split" },
  { id: "sprintf", href: "/detail/base/sprintf.html", texttag: "sprintf" },
  { id: "srcfile", href: "/detail/base/srcfile.html", texttag: "srcfile" },
  {
    id: "standardGeneric",
    href: "/detail/base/standardGeneric.html",
    texttag: "standardGeneric",
  },
  {
    id: "startsWith",
    href: "/detail/base/startsWith.html",
    texttag: "startsWith",
  },
  { id: "stop", href: "/detail/base/stop.html", texttag: "stop" },
  {
    id: "stopifnot",
    href: "/detail/base/stopifnot.html",
    texttag: "stopifnot",
  },
  { id: "strptime", href: "/detail/base/strptime.html", texttag: "strptime" },
  {
    id: "Character",
    href: "/detail/base/Character.html",
    texttag: "Character",
  },
  { id: "strrep", href: "/detail/base/strrep.html", texttag: "strrep" },
  { id: "strsplit", href: "/detail/base/strsplit.html", texttag: "strsplit" },
  { id: "strtoi", href: "/detail/base/strtoi.html", texttag: "strtoi" },
  { id: "strtrim", href: "/detail/base/strtrim.html", texttag: "strtrim" },
  { id: "Widths", href: "/detail/base/Widths.html", texttag: "Widths" },
  {
    id: "structure",
    href: "/detail/base/structure.html",
    texttag: "structure",
  },
  { id: "strwrap", href: "/detail/base/strwrap.html", texttag: "strwrap" },
  { id: "subset", href: "/detail/base/subset.html", texttag: "subset" },
  {
    id: "substitute",
    href: "/detail/base/substitute.html",
    texttag: "substitute",
  },
  { id: "substr", href: "/detail/base/substr.html", texttag: "substr" },
  { id: "sum", href: "/detail/base/sum.html", texttag: "sum" },
  { id: "summary", href: "/detail/base/summary.html", texttag: "summary" },
  { id: "svd", href: "/detail/base/svd.html", texttag: "svd" },
  { id: "sweep", href: "/detail/base/sweep.html", texttag: "sweep" },
  { id: "switch", href: "/detail/base/switch.html", texttag: "switch" },
  {
    id: "sys.parent",
    href: "/detail/base/sysparent.html",
    texttag: "sys.parent",
  },
  {
    id: "sys.source",
    href: "/detail/base/syssource.html",
    texttag: "sys.source",
  },
  { id: "system", href: "/detail/base/system.html", texttag: "system" },
  {
    id: "system.file",
    href: "/detail/base/systemfile.html",
    texttag: "system.file",
  },
  {
    id: "system.time",
    href: "/detail/base/systemtime.html",
    texttag: "system.time",
  },
  { id: "system2", href: "/detail/base/system2.html", texttag: "system2" },
  { id: "t", href: "/detail/base/t.html", texttag: "t" },
  { id: "table", href: "/detail/base/table.html", texttag: "table" },
  { id: "tabulate", href: "/detail/base/tabulate.html", texttag: "tabulate" },
  { id: "tapply", href: "/detail/base/tapply.html", texttag: "tapply" },
  {
    id: "taskCallbackManager",
    href: "/detail/base/taskCallbackManager.html",
    texttag: "taskCallbackManager",
  },
  { id: "tempfile", href: "/detail/base/tempfile.html", texttag: "tempfile" },
  {
    id: "textConnection",
    href: "/detail/base/textConnection.html",
    texttag: "textConnection",
  },
  { id: "tilde", href: "/detail/base/tilde.html", texttag: "tilde" },
  {
    id: "timezones",
    href: "/detail/base/timezones.html",
    texttag: "timezones",
  },
  { id: "toString", href: "/detail/base/toString.html", texttag: "toString" },
  { id: "topenv", href: "/detail/base/topenv.html", texttag: "topenv" },
  { id: "trace", href: "/detail/base/trace.html", texttag: "trace" },
  { id: "Function", href: "/detail/base/Function.html", texttag: "Function" },
  {
    id: "traceback",
    href: "/detail/base/traceback.html",
    texttag: "traceback",
  },
  { id: "tracemem", href: "/detail/base/tracemem.html", texttag: "tracemem" },
  {
    id: "transform",
    href: "/detail/base/transform.html",
    texttag: "transform",
  },
  { id: "trimws", href: "/detail/base/trimws.html", texttag: "trimws" },
  { id: "try", href: "/detail/base/try.html", texttag: "try" },
  { id: "typeof", href: "/detail/base/typeof.html", texttag: "typeof" },
  { id: "union", href: "/detail/base/union.html", texttag: "union" },
  { id: "unique", href: "/detail/base/unique.html", texttag: "unique" },
  { id: "unlink", href: "/detail/base/unlink.html", texttag: "unlink" },
  { id: "unlist", href: "/detail/base/unlist.html", texttag: "unlist" },
  { id: "unname", href: "/detail/base/unname.html", texttag: "unname" },
  {
    id: "utf8ToInt",
    href: "/detail/base/utf8ToInt.html",
    texttag: "utf8ToInt",
  },
  {
    id: "UTF-8-encoded",
    href: "/detail/base/UTF-8-encoded.html",
    texttag: "UTF-8-encoded",
  },
  {
    id: "validUTF8",
    href: "/detail/base/validUTF8.html",
    texttag: "validUTF8",
  },
  { id: "vector", href: "/detail/base/vector.html", texttag: "vector" },
  { id: "warning", href: "/detail/base/warning.html", texttag: "warning" },
  { id: "warnings", href: "/detail/base/warnings.html", texttag: "warnings" },
  { id: "weekdays", href: "/detail/base/weekdays.html", texttag: "weekdays" },
  { id: "which", href: "/detail/base/which.html", texttag: "which" },
  { id: "which.min", href: "/detail/base/whichmin.html", texttag: "which.min" },
  { id: "FALSE", href: "/detail/base/FALSE.html", texttag: "FALSE" },
  { id: "with", href: "/detail/base/with.html", texttag: "with" },
  {
    id: "withVisible",
    href: "/detail/base/withVisible.html",
    texttag: "withVisible",
  },
  { id: "write", href: "/detail/base/write.html", texttag: "write" },
  {
    id: "writeLines",
    href: "/detail/base/writeLines.html",
    texttag: "writeLines",
  },
  { id: "xtfrm", href: "/detail/base/xtfrm.html", texttag: "xtfrm" },
  { id: "zapsmall", href: "/detail/base/zapsmall.html", texttag: "zapsmall" },
];

var infocontent = document.getElementById("baseinfo");
for (let i = 0; i < librarylist.length; i++) {
  const basename = librarylist[i];
  const div = document.createElement("div");
  div.className = "lineitem";
  div.id = basename.id;
  div.style.display = "inline-block";
  div.style.width = "289px";
  div.style.height = "125px";
  div.style.fill = "none";

  const div2 = document.createElement("div");
  div2.className = "basenamebox";
  div2.style.width = "274.045px";
  div2.style.height = "100.124px";
  div2.style.borderRadius = "9.194px";
  div2.style.stroke = "#243D25";
  div2.style.strokeMiterlimit = "10";
  div2.style.strokeWidth = "1";
  div2.style.fontSize = "27px";
  div2.style.border = "1px solid #000";
  div2.style.transform = "translate(21.529px ,57.832px)";

  const atag = document.createElement("a");
  atag.href = basename.href;

  const txttag = document.createElement("text");
  const txtnode = document.createTextNode(basename.texttag);
  txttag.style.fontFamily = "ArialRoundedMTBold";

  txttag.appendChild(txtnode);
  atag.appendChild(txttag);
  div2.appendChild(atag);
  div.appendChild(div2);
  infocontent.appendChild(div);
}
